APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
GO_GOLANGCI_LINT_CLI_LINT_MODE: project
GO_REVIVE_CLI_LINT_MODE: project
GO_REVIVE_ARGUMENTS: ./...
